"""Test that generated prompts.py aligns with .claude/ agents and skills.

These tests validate that the build script correctly extracts and combines
agent/skill content into the prompts used by the containerized agent.
"""

import re
from pathlib import Path

import pytest


def test_prompts_file_exists():
    """Verify prompts.py exists and is importable."""
    prompts_file = Path("tektonit/prompts.py")
    assert prompts_file.exists(), "prompts.py should exist"

    # Should be importable
    from tektonit import prompts

    assert hasattr(prompts, "BATS_SYSTEM_PROMPT")
    assert hasattr(prompts, "PYTEST_SYSTEM_PROMPT")


def test_bats_prompt_has_key_concepts():
    """Verify BATS prompt includes key concepts from agents."""
    from tektonit.prompts import BATS_SYSTEM_PROMPT

    prompt_lower = BATS_SYSTEM_PROMPT.lower()

    # Core concepts from stepaction-test-generator
    assert "verbatim" in prompt_lower, "Should emphasize verbatim script embedding"
    assert "exact" in prompt_lower, "Should emphasize exact mocking/assertions"
    assert "mock" in prompt_lower, "Should cover mocking strategy"

    # Cross-platform from agents
    assert "macos" in prompt_lower or "cross-platform" in prompt_lower, "Should include cross-platform guidance"
    assert "sed -i" in BATS_SYSTEM_PROMPT, "Should mention sed -i'' -e pattern"

    # Test organization
    assert "suite" in prompt_lower, "Should mention test suite organization"


def test_pytest_prompt_has_key_concepts():
    """Verify pytest prompt includes key concepts from agents."""
    from tektonit.prompts import PYTEST_SYSTEM_PROMPT

    prompt_lower = PYTEST_SYSTEM_PROMPT.lower()

    # Core concepts
    assert "verbatim" in prompt_lower, "Should emphasize verbatim embedding"
    assert "textwrap.dedent" in prompt_lower or "textwrap" in prompt_lower, "Should use textwrap for Python scripts"
    assert "subprocess" in prompt_lower, "Should run scripts as subprocess"

    # Test organization
    assert "class" in prompt_lower, "Should organize into test classes"


def test_prompts_not_heavy_handed():
    """Verify prompts use explanatory style, not heavy-handed commands."""
    from tektonit.prompts import BATS_SYSTEM_PROMPT, PYTEST_SYSTEM_PROMPT

    combined = BATS_SYSTEM_PROMPT + PYTEST_SYSTEM_PROMPT

    # Count MUST/NEVER/ALWAYS (should be minimal, not dozens)
    must_count = len(re.findall(r"\bMUST\b", combined))
    never_count = len(re.findall(r"\bNEVER\b", combined))
    always_count = len(re.findall(r"\bALWAYS\b", combined))

    total_imperatives = must_count + never_count + always_count

    # Some imperative language is OK, but should be < 20% of what it was before (was ~50)
    assert total_imperatives < 15, (
        f"Prompts should use explanatory style, not heavy imperatives "
        f"(found {must_count} MUST, {never_count} NEVER, {always_count} ALWAYS)"
    )


@pytest.mark.skip(reason="Simplified prompts don't include reasoning explanations")
def test_prompts_have_reasoning():
    """Verify prompts explain WHY, not just WHAT."""
    pass


def test_prompts_file_is_generated():
    """Verify prompts.py has generation header."""
    prompts_file = Path("tektonit/prompts.py")
    content = prompts_file.read_text()

    assert "AUTO-GENERATED" in content, "prompts.py should indicate it's generated"
    assert ".claude/" in content, "prompts.py should reference .claude/ as source"
    assert "DO NOT EDIT THIS FILE DIRECTLY" in content, "prompts.py should warn against direct edits"


@pytest.mark.skip(reason="Simplified prompts don't include templates")
def test_prompts_preserve_templates():
    """Verify build script preserves template strings."""
    pass


@pytest.mark.skip(reason="Simplified prompts don't include helper functions")
def test_prompts_preserve_helper_functions():
    """Verify build script preserves helper functions."""
    pass


def test_agent_source_files_exist():
    """Verify the source .claude/ files exist."""
    required_sources = [
        ".claude/agents/stepaction-test-generator.md",
        ".claude/agents/task-test-generator.md",
        ".claude/skills/fix-test.md",
        ".claude/skills/diagnose-failure.md",
    ]

    for source in required_sources:
        assert Path(source).exists(), f"Source file should exist: {source}"


def test_build_script_exists():
    """Verify build script is present and executable."""
    build_script = Path("scripts/build_prompts_from_agents.py")
    assert build_script.exists(), "Build script should exist"

    sync_script = Path("scripts/sync-prompts.sh")
    assert sync_script.exists(), "Sync script should exist"

    # Check executable bit
    import os

    assert os.access(build_script, os.X_OK), "Build script should be executable"
    assert os.access(sync_script, os.X_OK), "Sync script should be executable"


@pytest.mark.integration
def test_can_regenerate_prompts():
    """Integration test: verify we can regenerate prompts."""
    import subprocess
    import sys

    result = subprocess.run([sys.executable, "scripts/build_prompts_from_agents.py"], capture_output=True, text=True)

    assert result.returncode == 0, f"Build script should succeed:\n{result.stderr}"
    assert "SUCCESS" in result.stdout, "Build script should report success"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
