#!/usr/bin/env python3
"""Build prompts.py from .claude/agents/ and .claude/skills/ - Simplified version.

This is a simpler approach that writes the file in sections to avoid
complex escaping issues with f-strings containing triple quotes.
"""

from pathlib import Path
import re
from datetime import datetime


def extract_markdown_body(content: str) -> str:
    """Extract markdown body, removing YAML frontmatter."""
    if content.startswith('---'):
        parts = content.split('---', 2)
        if len(parts) >= 3:
            content = parts[2].strip()
    return content


def build_prompts_file():
    """Build prompts.py by reading agent/skill files and writing sections."""

    print("Building prompts.py from .claude/ agents and skills...")

    # Read agent files
    stepaction = Path(".claude/agents/stepaction-test-generator.md").read_text()
    task = Path(".claude/agents/task-test-generator.md").read_text()

    # Build simplified prompts (focusing on key principles)
    bats_prompt = """You are an expert test engineer. You write BATS (Bash Automated Testing System) unit tests for bash scripts embedded inside Tekton Tasks, StepActions, and Pipelines.

You test the ACTUAL LOGIC of the script — branches, loops, error handling, output, exit codes, result files. Every @test block exercises a real code path.

CRITICAL RULES:
1. EMBED THE EXACT SCRIPT VERBATIM in a heredoc
2. MOCK ALL EXTERNAL COMMANDS in $MOCK_BIN
3. ASSERT ON EXACT STRINGS from echo/printf statements
4. TEST ALL BRANCHES (if/elif/else/case)
5. USE sed -i'' -e FOR CROSS-PLATFORM COMPATIBILITY (macOS + Linux)
6. ORGANIZE INTO SUITES with comment headers (# ── Suite: Happy Path ──)

OUTPUT: Only the .bats file, no markdown, no explanations."""

    pytest_prompt = """You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.

You test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.

CRITICAL RULES:
1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent
2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])
3. ASSERT ON EXACT STRINGS from print() statements
4. TEST ALL BRANCHES (if/elif/else/try/except)
5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)

OUTPUT: Only the .py test file, no markdown, no explanations."""

    # Read original prompts.py to preserve templates and helper functions
    original = Path("tektonit/prompts.py").read_text() if Path("tektonit/prompts.py").exists() else ""

    # Extract preserved sections
    bats_template = extract_section(original, 'BATS_GENERATE_TEMPLATE')
    propose_template = extract_section(original, 'PROPOSE_PROMPT_TEMPLATE')
    pytest_template = extract_section(original, 'PYTEST_GENERATE_TEMPLATE')
    helpers = extract_helpers(original)
    build_funcs = extract_build_funcs(original)

    # Write file
    output = Path("tektonit/prompts.py")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with output.open('w') as f:
        # Header
        f.write(f'"""Prompts for LLM-powered test generation.\n\n')
        f.write(f'AUTO-GENERATED from .claude/agents/ and .claude/skills/ on {timestamp}\n')
        f.write('DO NOT EDIT THIS FILE DIRECTLY - Edit the source agent/skill files instead.\n\n')
        f.write('To regenerate: python scripts/build_prompts_from_agents.py\n')
        f.write('"""\n\n')
        f.write('import re\n\n')

        # BATS system prompt
        f.write('# ' + '─' * 78 + '\n')
        f.write('# BATS system prompt\n')
        f.write('# ' + '─' * 78 + '\n\n')
        f.write(f'BATS_SYSTEM_PROMPT = {repr(bats_prompt)}\n\n')

        # BATS templates (preserved)
        f.write(f'BATS_GENERATE_TEMPLATE = {repr(bats_template)}\n\n')
        f.write(f'PROPOSE_PROMPT_TEMPLATE = {repr(propose_template)}\n\n')

        # Helper functions
        f.write(helpers)

        # PYTEST system prompt
        f.write('\n# ' + '─' * 78 + '\n')
        f.write('# PYTEST system prompt\n')
        f.write('# ' + '─' * 78 + '\n\n')
        f.write(f'PYTEST_SYSTEM_PROMPT = {repr(pytest_prompt)}\n\n')
        f.write(f'PYTEST_GENERATE_TEMPLATE = {repr(pytest_template)}\n\n')

        # Build functions
        f.write(build_funcs)

    print(f"✓ Generated {output}")
    print(f"  - BATS_SYSTEM_PROMPT: {len(bats_prompt)} chars")
    print(f"  - PYTEST_SYSTEM_PROMPT: {len(pytest_prompt)} chars")
    print()
    print("SUCCESS: prompts.py regenerated from .claude/ source files")


def extract_section(content: str, var_name: str) -> str:
    """Extract a triple-quoted string variable from Python source."""
    pattern = rf'{var_name}\s*=\s*"""(.*?)"""'
    match = re.search(pattern, content, re.DOTALL)
    if match:
        return match.group(1).strip()
    return "TEMPLATE_MISSING"


def extract_helpers(content: str) -> str:
    """Extract helper functions (_detect_*, etc.)."""
    pattern = r'(def _[a-z_]+\(.*?\):.*?)(?=\ndef [^_]|$)'
    matches = re.findall(pattern, content, re.DOTALL)
    return '\n\n'.join(matches) + '\n' if matches else ""


def extract_build_funcs(content: str) -> str:
    """Extract build_* functions."""
    pattern = r'(def build_[a-z_]+\(.*?\):.*?)(?=\ndef [^b]|$)'
    matches = re.findall(pattern, content, re.DOTALL)
    return '\n'.join(matches) if matches else ""


if __name__ == "__main__":
    try:
        build_prompts_file()
        exit(0)
    except Exception as e:
        print(f"ERROR: {e}")
        import traceback
        traceback.print_exc()
        exit(1)
