#!/usr/bin/env python3
"""Build prompts.py from .claude/agents/ and .claude/skills/.

This script generates a clean prompts.py with ONLY the system prompts.
No helper functions or templates are included - keeping it minimal and clean.
"""

from pathlib import Path


def extract_content_from_markdown(filepath: Path) -> str:
    """Extract main content from agent/skill markdown file (skip frontmatter)."""
    with open(filepath) as f:
        content = f.read()

    # Skip YAML frontmatter (between --- markers)
    parts = content.split("---", 2)
    if len(parts) >= 3:
        # Content after second ---
        return parts[2].strip()
    else:
        # No frontmatter, return as-is
        return content.strip()


def build_prompts_file():
    """Build prompts.py by reading agent/skill files and writing sections."""

    print("Building prompts.py from .claude/ agents and skills...")

    # Read agents and skills from .claude/
    agents_dir = Path(".claude/agents")
    Path(".claude/skills")

    prompts = {}

    # Read specific agents we need for prompts
    agent_files = {
        "BATS_SYSTEM_PROMPT": None,  # Will use hardcoded for now
        "PYTEST_SYSTEM_PROMPT": None,  # Will use hardcoded for now
        "TEKTON_LINTER_PROMPT": agents_dir / "tekton-linter.md",
        "FAILURE_ANALYST_PROMPT": agents_dir / "failure-analyst.md",
        "TEST_GENERATOR_PROMPT": agents_dir / "test-generator.md",
    }

    # Hardcoded BATS and PYTEST prompts (simplified versions)
    prompts["BATS_SYSTEM_PROMPT"] = (
        """You are an expert test engineer. You write BATS (Bash Automated Testing System) """
        """unit tests for bash scripts embedded inside Tekton Tasks, StepActions, and Pipelines.

You test the ACTUAL LOGIC of the script — branches, loops, error handling, output, exit codes, """
        """result files. Every @test block exercises a real code path with realistic scenarios.

CRITICAL RULES:
1. EMBED THE EXACT SCRIPT VERBATIM in a heredoc
2. MOCK ALL EXTERNAL COMMANDS in $MOCK_BIN with exact invocation matching
3. ASSERT ON EXACT STRINGS from echo/printf (both stdout and stderr)
4. TEST ALL CODE PATHS:
   - Happy path: script succeeds with valid input
   - Error paths: each if/else/case branch, failure conditions
   - Edge cases: empty files, missing files, invalid/malformed input
   - Exit codes: verify correct propagation for different failure scenarios
5. USE sed -i'' -e FOR CROSS-PLATFORM COMPATIBILITY (macOS + Linux)
6. ORGANIZE INTO SUITES with comment headers (# ── Suite: Happy Path ──)

OUTPUT: Only the .bats file, no markdown, no explanations."""
    )

    prompts["PYTEST_SYSTEM_PROMPT"] = (
        """You are an expert test engineer. You write pytest unit tests for Python scripts """
        """embedded inside Tekton Tasks, StepActions, and Pipelines.

You test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.

CRITICAL RULES:
1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent
2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])
3. ASSERT ON EXACT STRINGS from print() statements
4. TEST ALL BRANCHES (if/elif/else/try/except)
5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)

OUTPUT: Only the .py test file, no markdown, no explanations."""
    )

    # Read agent files
    for prompt_name, filepath in agent_files.items():
        if filepath and filepath.exists():
            content = extract_content_from_markdown(filepath)
            prompts[prompt_name] = content
            print(f"  ✓ Loaded {filepath.name} ({len(content)} chars)")
        elif filepath:
            print(f"  ⚠ Skipping {filepath.name} (not found)")
            prompts[prompt_name] = ""  # Empty if file doesn't exist

    # Write file
    output = Path("tektonit/prompts.py")

    with output.open("w") as f:
        # Header
        f.write('"""Prompts for LLM-powered test generation and validation.\n\n')
        f.write("AUTO-GENERATED from .claude/agents/ and .claude/skills/\n")
        f.write("DO NOT EDIT THIS FILE DIRECTLY - Edit the source agent/skill files instead.\n\n")
        f.write("To regenerate: python scripts/build_prompts_from_agents.py\n")
        f.write('"""\n\n')
        f.write("# ruff: noqa: E501\n\n")

        # Write all prompts
        prompt_order = [
            ("BATS_SYSTEM_PROMPT", "BATS system prompt"),
            ("PYTEST_SYSTEM_PROMPT", "PYTEST system prompt"),
            ("TEKTON_LINTER_PROMPT", "Tekton YAML linter prompt"),
            ("FAILURE_ANALYST_PROMPT", "Failure analyst prompt"),
            ("TEST_GENERATOR_PROMPT", "Test generator prompt"),
        ]

        for prompt_name, prompt_label in prompt_order:
            if prompt_name in prompts and prompts[prompt_name]:
                f.write("# " + "─" * 78 + "\n")
                f.write(f"# {prompt_label}\n")
                f.write("# " + "─" * 78 + "\n\n")

                # Escape the prompt content for Python string
                escaped = prompts[prompt_name].replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
                f.write(f'{prompt_name} = "{escaped}"\n\n')

        # Add stub functions for backward compatibility
        f.write("\n# " + "─" * 78 + "\n")
        f.write("# Stub functions for backward compatibility with test_generator module\n")
        f.write("# " + "─" * 78 + "\n\n\n")
        f.write("def build_bats_prompt(resource, yaml_content=None):\n")
        f.write('    """Stub function - returns BATS system prompt."""\n')
        f.write("    return BATS_SYSTEM_PROMPT\n\n\n")
        f.write("def build_pytest_prompt(resource, yaml_content=None):\n")
        f.write('    """Stub function - returns pytest system prompt."""\n')
        f.write("    return PYTEST_SYSTEM_PROMPT\n\n\n")
        f.write("def build_propose_prompt(resource):\n")
        f.write('    """Stub function - returns empty string."""\n')
        f.write('    return ""\n\n\n')
        f.write("def get_script_languages(resource):\n")
        f.write('    """Stub function - returns bash."""\n')
        f.write('    return ["bash"]\n\n\n')
        f.write("def has_testable_scripts(resource):\n")
        f.write('    """Stub function - returns True."""\n')
        f.write("    return True\n")

    print(f"✓ Generated {output}")
    prompt_names = [
        "BATS_SYSTEM_PROMPT",
        "PYTEST_SYSTEM_PROMPT",
        "TEKTON_LINTER_PROMPT",
        "FAILURE_ANALYST_PROMPT",
        "TEST_GENERATOR_PROMPT",
    ]
    for prompt_name in prompt_names:
        if prompt_name in prompts and prompts[prompt_name]:
            print(f"  - {prompt_name}: {len(prompts[prompt_name])} chars")

    # Format with ruff if available (optional - for local dev)
    try:
        import subprocess

        result = subprocess.run(["ruff", "format", str(output)], capture_output=True, check=False)
        if result.returncode == 0:
            print("  - Formatted with ruff")
    except FileNotFoundError:
        # ruff not available (e.g., in Docker build) - that's OK
        pass

    print()
    print("SUCCESS: prompts.py regenerated from .claude/ source files")


if __name__ == "__main__":
    try:
        build_prompts_file()
        exit(0)
    except Exception as e:
        print(f"ERROR: {e}")
        import traceback

        traceback.print_exc()
        exit(1)
