#!/usr/bin/env python3
"""Build prompts.py from .claude/agents/ and .claude/skills/.

This script generates a clean prompts.py with ONLY the system prompts.
No helper functions or templates are included - keeping it minimal and clean.
"""

from pathlib import Path


def build_prompts_file():
    """Build prompts.py by reading agent/skill files and writing sections."""

    print("Building prompts.py from .claude/ agents and skills...")

    # Build simplified system prompts
    # ruff: noqa: E501
    bats_prompt = """You are an expert test engineer. You write BATS (Bash Automated Testing System) unit tests for bash scripts embedded inside Tekton Tasks, StepActions, and Pipelines.

You test the ACTUAL LOGIC of the script — branches, loops, error handling, output, exit codes, result files. Every @test block exercises a real code path.

CRITICAL RULES:
1. EMBED THE EXACT SCRIPT VERBATIM in a heredoc
2. MOCK ALL EXTERNAL COMMANDS in $MOCK_BIN
3. ASSERT ON EXACT STRINGS from echo/printf statements
4. TEST ALL BRANCHES (if/elif/else/case)
5. USE sed -i'' -e FOR CROSS-PLATFORM COMPATIBILITY (macOS + Linux)
6. ORGANIZE INTO SUITES with comment headers (# ── Suite: Happy Path ──)

OUTPUT: Only the .bats file, no markdown, no explanations."""

    pytest_prompt = """You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.

You test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.

CRITICAL RULES:
1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent
2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])
3. ASSERT ON EXACT STRINGS from print() statements
4. TEST ALL BRANCHES (if/elif/else/try/except)
5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)

OUTPUT: Only the .py test file, no markdown, no explanations."""

    # Write file
    output = Path("tektonit/prompts.py")

    with output.open("w") as f:
        # Header
        f.write('"""Prompts for LLM-powered test generation.\n\n')
        f.write("AUTO-GENERATED from .claude/agents/ and .claude/skills/\n")
        f.write("DO NOT EDIT THIS FILE DIRECTLY - Edit the source agent/skill files instead.\n\n")
        f.write("To regenerate: python scripts/build_prompts_from_agents.py\n")
        f.write('"""\n\n')
        f.write("# ruff: noqa: E501\n\n")

        # BATS system prompt
        f.write("# " + "─" * 78 + "\n")
        f.write("# BATS system prompt\n")
        f.write("# " + "─" * 78 + "\n\n")
        # Use triple-quoted strings to avoid quote escaping inconsistencies across Python versions
        f.write('BATS_SYSTEM_PROMPT = """')
        f.write(bats_prompt.replace('\\', '\\\\').replace('"""', r'\"\"\"'))
        f.write('"""\n\n')

        # PYTEST system prompt
        f.write("# " + "─" * 78 + "\n")
        f.write("# PYTEST system prompt\n")
        f.write("# " + "─" * 78 + "\n\n")
        # Use triple-quoted strings to avoid quote escaping inconsistencies across Python versions
        f.write('PYTEST_SYSTEM_PROMPT = """')
        f.write(pytest_prompt.replace('\\', '\\\\').replace('"""', r'\"\"\"'))
        f.write('"""\n')

    print(f"✓ Generated {output}")
    print(f"  - BATS_SYSTEM_PROMPT: {len(bats_prompt)} chars")
    print(f"  - PYTEST_SYSTEM_PROMPT: {len(pytest_prompt)} chars")

    # Format with ruff if available (optional - for local dev)
    try:
        import subprocess

        result = subprocess.run(["ruff", "format", str(output)], capture_output=True, check=False)
        if result.returncode == 0:
            print("  - Formatted with ruff")
    except FileNotFoundError:
        # ruff not available (e.g., in Docker build) - that's OK
        pass

    print()
    print("SUCCESS: prompts.py regenerated from .claude/ source files")


if __name__ == "__main__":
    try:
        build_prompts_file()
        exit(0)
    except Exception as e:
        print(f"ERROR: {e}")
        import traceback

        traceback.print_exc()
        exit(1)
