"""Prompts for LLM-powered test generation.

AUTO-GENERATED from .claude/agents/ and .claude/skills/ on 2026-03-23 08:11:58
DO NOT EDIT THIS FILE DIRECTLY - Edit the source agent/skill files instead.

To regenerate: python scripts/build_prompts_from_agents.py
"""

import re

# ──────────────────────────────────────────────────────────────────────────────
# BATS system prompt
# ──────────────────────────────────────────────────────────────────────────────

BATS_SYSTEM_PROMPT = "You are an expert test engineer. You write BATS (Bash Automated Testing System) unit tests for bash scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — branches, loops, error handling, output, exit codes, result files. Every @test block exercises a real code path.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM in a heredoc\n2. MOCK ALL EXTERNAL COMMANDS in $MOCK_BIN\n3. ASSERT ON EXACT STRINGS from echo/printf statements\n4. TEST ALL BRANCHES (if/elif/else/case)\n5. USE sed -i'' -e FOR CROSS-PLATFORM COMPATIBILITY (macOS + Linux)\n6. ORGANIZE INTO SUITES with comment headers (# ── Suite: Happy Path ──)\n\nOUTPUT: Only the .bats file, no markdown, no explanations."

BATS_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'

PROPOSE_PROMPT_TEMPLATE = 'TEMPLATE_MISSING'

def _detect_script_language(script: str) -> str:
    """Detect script language from shebang or content."""
    first_line = script.strip().split("\n")[0] if script.strip() else ""
    if "python" in first_line:
        return "python"
    return "bash"


def _detect_commands_in_script(script: str) -> list[str]:
    """Detect external commands used in a bash script that need mocking."""
    known_commands = [
        "kubectl", "oc", "curl", "git", "oras", "jq", "yq",
        "aws", "rosa", "gh", "docker", "podman", "skopeo",
        "pip", "npm", "make", "helm", "kustomize", "cosign",
        "tkn", "base64", "openssl", "wget", "shellcheck",
        "hadolint", "find", "date", "readlink", "sleep",
    ]
    found = []
    for cmd in known_commands:
        if re.search(rf"\b{cmd}\b", script):
            found.append(cmd)
    return found


def _detect_env_vars_in_resource(resource) -> list[dict]:
    """Detect environment variables defined in steps that need mocking."""
    env_vars = []
    for step in resource.steps:
        for env in step.env:
            entry = {"name": env.get("name", ""), "source": "direct"}
            value_from = env.get("valueFrom", {})
            if value_from.get("fieldRef"):
                entry["source"] = "fieldRef"
                entry["field"] = value_from["fieldRef"].get("fieldPath", "")
            elif value_from.get("secretKeyRef"):
                entry["source"] = "secretKeyRef"
                entry["secret"] = value_from["secretKeyRef"].get("name", "")
                entry["key"] = value_from["secretKeyRef"].get("key", "")
            elif env.get("value"):
                entry["source"] = "value"
                entry["value"] = env["value"]
            env_vars.append(entry)
    return env_vars


def _build_env_mock_section(resource) -> str:
    """Build environment variable mocking instructions."""
    env_vars = _detect_env_vars_in_resource(resource)
    if not env_vars:
        # Check for env vars referenced directly in scripts
        lines = []
        for _, script in resource.embedded_scripts:
            for match in re.findall(r'\$\{?([A-Z][A-Z0-9_]+)\}?', script):
                if match not in ("PATH", "HOME", "PWD", "SHELL", "USER", "TMPDIR",
                                 "BASH_COMMAND", "LINENO", "PIPESTATUS", "IFS",
                                 "FUNCNAME", "BASH_SOURCE", "OSTYPE", "HOSTNAME",
                                 "SCRIPT_EOF", "EOF", "MOCK_EOF"):
                    lines.append(f'- Export `{match}`: `export {match}="test-value"`')
        seen = set()
        unique = []
        for line in lines:
            if line not in seen:
                seen.add(line)
                unique.append(line)
        return "\n".join(unique) if unique else "- No environment variables to mock"

    lines = []
    for env in env_vars:
        name = env["name"]
        if env["source"] == "fieldRef":
            lines.append(f'- Export `{name}` (fieldRef: {env.get("field", "")}): '
                         f'`export {name}="test-value"`')
        elif env["source"] == "secretKeyRef":
            lines.append(f'- Export `{name}` (secret): `export {name}="mock-secret"`')
        elif env["source"] == "value":
            val = env.get("value", "")
            if "$(params." in val:
                lines.append(f'- Export `{name}`: `export {name}="test-param-value"`')
            else:
                lines.append(f'- Export `{name}`: already set to `"{val}"`')
        else:
            lines.append(f'- Export `{name}`: `export {name}="test-value"`')
    return "\n".join(lines)


def _build_result_verification(resource) -> str:
    """Build result verification instructions."""
    results = resource.results
    if not results:
        # Check for result references in scripts
        all_refs = set()
        for _, script in resource.embedded_scripts:
            all_refs.update(re.findall(r'\$\((?:step\.)?results\.([a-zA-Z0-9_-]+)\.path\)', script))
        if all_refs:
            lines = [f'- Verify result file `{r}` is written with expected content' for r in sorted(all_refs)]
            return "\n".join(lines)
        return "- No results to verify"

    lines = []
    for r in results:
        lines.append(f'- Verify `{r.name}`: `[ -f "$RESULTS_DIR/{r.name}" ]` and check content')
    return "\n".join(lines)


def _extract_exact_outputs(script: str) -> list[str]:
    """Extract exact echo/printf strings from script for precise assertion guidance."""
    outputs = []
    seen_prefixes = set()
    # Match echo with various flag combinations and quoting styles
    for match in re.finditer(r'echo\s+(?:-[en]+\s+)?"([^"]*)"', script):
        msg = match.group(1).strip()
        if not msg or len(msg) < 4:
            continue
        # Use first 30 chars as dedup key to avoid near-duplicates
        prefix = msg[:30]
        if prefix not in seen_prefixes:
            seen_prefixes.add(prefix)
            outputs.append(msg)
    return outputs


def _extract_exact_branches(script: str) -> list[str]:
    """Extract exact if/elif conditions from script for precise test case mapping."""
    branches = []
    for match in re.finditer(r'if\s+\[\[?\s*(.*?)\s*\]?\];?\s*then', script):
        cond = match.group(1).strip()[:100]
        branches.append(cond)
    for match in re.finditer(r'elif\s+\[\[?\s*(.*?)\s*\]?\];?\s*then', script):
        cond = match.group(1).strip()[:100]
        branches.append(cond)
    return branches


def _build_test_cases(resource, scripts: list[tuple[str, str]]) -> str:
    """Build test case descriptions based on actual script analysis."""
    cases = []
    for step_name, script in scripts:
        if _detect_script_language(script) != "bash":
            continue

        cases.append(f"\n#### Step: {step_name}")

        # Extract exact branches for precise test case mapping
        branches = _extract_exact_branches(script)
        if branches:
            cases.append("Exact branches found in script (write a @test for EACH):")
            for i, cond in enumerate(branches, 1):
                cases.append(f"  {i}. `{cond}` → test TRUE path AND FALSE path")

        # Extract exact output strings for assertion guidance
        outputs = _extract_exact_outputs(script)
        if outputs:
            cases.append("Exact output strings to assert on (copy these into assertions):")
            for msg in outputs[:15]:  # cap at 15
                # Show a prefix suitable for assertion matching
                prefix = msg.split("$")[0].rstrip() if "$" in msg else msg
                if prefix:
                    cases.append(f'  - `[[ "$output" == *"{prefix}"* ]]`')

        if "while " in script or "for " in script:
            cases.append("- Test loop with 0, 1, and multiple iterations")
        if "while true" in script or "until " in script or "while !" in script:
            cases.append(
                "- CRITICAL: Mock the loop exit condition so it breaks on FIRST iteration. "
                "Mock sleep as no-op. Never let a test hang."
            )
        if "exit " in script:
            # Extract exact exit codes
            exit_codes = set(re.findall(r'exit\s+(\d+)', script))
            if exit_codes:
                cases.append(f"- Test each exit code: {', '.join(sorted(exit_codes))}")
            else:
                cases.append("- Test each exit code path")
        if "jq " in script:
            cases.append("- Test JSON parsing: valid JSON, empty input, missing keys")
        if "curl " in script:
            cases.append("- Test HTTP mock: success (200), failure (500), empty body")
        if "kubectl " in script or "oc " in script:
            cases.append("- Test k8s mock: success with data, empty results, command failure")
        if "set -e" in script or "set -euo pipefail" in script:
            cases.append("- Verify script aborts on command failure (set -e)")
        if "trap " in script:
            cases.append("- Verify trap handler runs on error/exit")
        if "$(results." in script or "$(step.results." in script:
            cases.append("- Verify result files written with correct content")
        if "SNAPSHOT" in script:
            cases.append("- Test SNAPSHOT JSON: valid, empty components array, missing component")
        if "retry" in script.lower() or "attempt" in script.lower():
            cases.append("- Test retry: succeed on first try, fail all retries")

        cases.append("- Test happy path (all inputs valid, commands succeed)")
        cases.append("- Test with missing/empty required inputs")

    return "\n".join(cases) if cases else "- Test the main execution path\n- Test error handling"


def _mock_strategy_for_kind(resource) -> str:
    """Return resource-type-specific mock strategy."""
    kind = resource.kind

    if kind == "StepAction":
        return """\
StepActions have a SINGLE script:
- Embed the full script via heredoc in setup()
- Mock all external CLI tools in $MOCK_BIN
- sed-replace $(params.X) and $(results.X.path) with temp paths
- Export env vars the script reads
- Test as standalone executable"""

    elif kind == "Task":
        steps_info = []
        for s in resource.steps:
            if s.script:
                steps_info.append(f"  - Step '{s.name}': inline script → TEST THIS")
            elif s.ref:
                steps_info.append(f"  - Step '{s.name}': uses ref → SKIP (tested separately)")
        steps_str = "\n".join(steps_info) if steps_info else "  - No inline scripts"

        return f"""\
Tasks have MULTIPLE steps — test each inline script independently:
{steps_str}

Per step:
- Embed that step's script in its own setup()
- Create temp /workspace/ dirs to simulate shared workspaces
- Create temp files for volume mounts (secrets, configmaps)
- Mock env vars from fieldRef/secretKeyRef
- Each step gets its own @test blocks"""

    elif kind in ("Pipeline", "PipelineRun"):
        return """\
Pipelines/PipelineRuns are mostly declarative. Only test inline scripts \
if present in taskSpec blocks."""

    return "- Mock external commands in $MOCK_BIN"


def _build_script_analysis(bash_scripts: list[tuple[str, str]]) -> str:
    """Run static analysis on scripts and format for the prompt."""
    from tektonit.script_analyzer import analyze_script

    parts = []
    for step_name, script in bash_scripts:
        analysis = analyze_script(script)
        parts.append(f"### Step: {step_name}")
        parts.append(analysis.to_prompt_section())
    return "\n\n".join(parts) if parts else "No detailed analysis available."


def _find_few_shot_example(resource) -> str:
    """Find a real passing BATS test from the catalog to use as few-shot example.

    Looks for existing sanity-check/*.bats files near the resource,
    walking up the directory tree to find one from a sibling resource.
    """
    from pathlib import Path

    source = Path(resource.source_path)

    # Search strategy: look for .bats files in nearby sanity-check/ dirs
    # 1. Same resource type directory (e.g., stepactions/*/0.1/sanity-check/)
    # 2. Same top-level category (e.g., stepactions/)
    search_roots = [
        source.parent.parent.parent,  # e.g., stepactions/
        source.parent.parent.parent.parent,  # e.g., catalog root
    ]

    for root in search_roots:
        if not root.exists():
            continue
        for bats_file in sorted(root.rglob("sanity-check/*.bats")):
            # Don't use the resource's own test as example
            if bats_file.parent.parent == source.parent:
                continue
            content = bats_file.read_text()
            # Only use tests that look complete (have setup, teardown, @test)
            if "setup()" in content and "teardown()" in content and "@test" in content:
                # Truncate if too long (keep first 150 lines)
                lines = content.splitlines()
                if len(lines) > 150:
                    content = "\n".join(lines[:150]) + "\n# ... (truncated)"
                return f"```bats\n{content}\n```"

    return "(No reference example available in the catalog — follow the system prompt patterns)"


def _build_sed_replacements(resource, bash_scripts: list[tuple[str, str]]) -> str:
    """Extract exact $(params.X), $(results.X.path) patterns from scripts for sed instructions."""
    params_found = set()
    results_found = set()
    step_results_found = set()
    paths_found = set()

    for _, script in bash_scripts:
        # Extract exact param references
        for m in re.findall(r'\$\(params\.([a-zA-Z0-9_-]+)\)', script):
            params_found.add(m)
        # Extract exact result references
        for m in re.findall(r'\$\(results\.([a-zA-Z0-9_-]+)\.path\)', script):
            results_found.add(m)
        # Extract exact step.result references
        for m in re.findall(r'\$\(step\.results\.([a-zA-Z0-9_-]+)\.path\)', script):
            step_results_found.add(m)
        # Extract hardcoded paths
        if '/tekton/steps/' in script:
            paths_found.add('/tekton/steps/')
        if '/workspace/' in script:
            paths_found.add('/workspace/')
        for m in re.findall(r'(/[a-z]+/[a-z-]+/)', script):
            if m not in ('/usr/bin/', '/usr/local/', '/dev/null/'):
                paths_found.add(m)

    lines = []
    for p in sorted(params_found):
        # Suggest a realistic test value based on param name
        if 'url' in p.lower() or 'ref' in p.lower() or 'oci' in p.lower():
            val = "quay.io/test/repo:tag"
        elif 'path' in p.lower() or 'dir' in p.lower():
            val = "$TEST_TEMP_DIR/workdir"
        elif 'name' in p.lower():
            val = "test-resource-name"
        elif 'pass' in p.lower() or 'bool' in p.lower():
            val = "true"
        else:
            val = f"test-{p}-value"
        lines.append(f'- `sed -i\'\' -e "s|$(params.{p})|{val}|g" "$SCRIPT_FILE"`')
    for r in sorted(results_found):
        lines.append(f'- `sed -i\'\' -e "s|$(results.{r}.path)|$RESULTS_DIR/{r}|g" "$SCRIPT_FILE"`')
    for r in sorted(step_results_found):
        lines.append(f'- `sed -i\'\' -e "s|$(step.results.{r}.path)|$RESULTS_DIR/{r}|g" "$SCRIPT_FILE"`')
    for p in sorted(paths_found):
        lines.append(f'- `sed -i\'\' -e "s|{p}|$TEST_TEMP_DIR{p}|g" "$SCRIPT_FILE"`')

    if not lines:
        return "- No Tekton variable substitutions needed"
    return "\n".join(lines)



def _build_python_test_cases(resource, scripts: list[tuple[str, str]]) -> str:
    """Build test case descriptions for Python scripts."""
    cases = []
    for step_name, script in scripts:
        if _detect_script_language(script) != "python":
            continue

        cases.append(f"\n#### Step: {step_name}")

        # Extract branches
        for match in re.finditer(r'^\s*if\s+(.+?):', script, re.MULTILINE):
            cond = match.group(1).strip()[:80]
            cases.append(f"  - Branch: `{cond}` → test TRUE and FALSE")

        # Extract try/except
        if "try:" in script:
            cases.append("- Test try/except: success path AND exception path")
        if "sys.exit(" in script:
            exit_codes = set(re.findall(r'sys\.exit\((\d+)\)', script))
            if exit_codes:
                cases.append(f"- Test exit codes: {', '.join(sorted(exit_codes))}")
        if "print(" in script:
            cases.append("- Verify stdout print messages match exact strings from script")
        if "urllib" in script or "requests" in script or "http" in script:
            cases.append("- Mock HTTP calls: test success response and failure response")
        if "os.getenv" in script or "os.environ" in script:
            cases.append("- Test with missing environment variables")
        if "sys.argv" in script:
            cases.append("- Test with different command-line arguments")
        if "$(results." in script or "$(step.results." in script:
            cases.append("- Verify result files written with correct content")

        cases.append("- Test happy path (all inputs valid)")
        cases.append("- Test with missing/invalid inputs")

    return "\n".join(cases) if cases else "- Test the main execution path\n- Test error handling"


def _build_python_tekton_replacements(resource, scripts: list[tuple[str, str]]) -> str:
    """Extract $(params.X) and $(results.X.path) patterns from Python scripts."""
    lines = []
    for _, script in scripts:
        if _detect_script_language(script) != "python":
            continue
        for m in sorted(set(re.findall(r'\$\(params\.([a-zA-Z0-9_-]+)\)', script))):
            lines.append(f'- `script_content = script_content.replace("$(params.{m})", "test-{m}-value")`')
        for m in sorted(set(re.findall(r'\$\(results\.([a-zA-Z0-9_-]+)\.path\)', script))):
            lines.append(f'- `script_content = script_content.replace("$(results.{m}.path)", str(tmp_path / "{m}"))`')
        for m in sorted(set(re.findall(r'\$\(step\.results\.([a-zA-Z0-9_-]+)\.path\)', script))):
            lines.append(
                f'- `script_content = script_content.replace('
                f'"$(step.results.{m}.path)", str(tmp_path / "{m}"))`'
            )
    return "\n".join(lines) if lines else "- No Tekton variable replacements needed"



# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = '\\\nGenerate pytest unit tests for the Python script(s) in this Tekton {kind}.\n\n## Resource YAML\n```yaml\n{yaml_content}\n```\n\n## Resource Info\n- Kind: {kind}\n- Name: {name}\n- File: {source_path}\n- Scripts to test: {script_info}\n\n## setup (fixture) must:\n1. Embed the EXACT script in a fixture using textwrap.dedent\n2. Replace $(params.X) with concrete test values\n3. Replace $(results.X.path) with tmp_path file paths\n4. Set environment variables the script reads\n5. Return (script_file, env, tmp_path)\n\n## Run strategy\n- Execute the script via subprocess.run([sys.executable, script_file])\n- Capture stdout, stderr, returncode\n- Use timeout=30 to prevent hangs\n\n## Tekton variable replacements\n{tekton_replacements}\n\n## Environment variables to set\n{env_section}\n\n## Results to verify\n{result_verification}\n\n## Test cases — test the ACTUAL LOGIC\n{test_cases}\n\n## Edge cases\n- Missing/empty required environment variables\n- Network calls failing (mock or skip)\n- Invalid input data (malformed JSON, empty strings)\n- Scripts with sys.exit(): verify returncode matches exit code\n- Result files: verify content is written correctly\n\nOutput ONLY the .py test file. No markdown, no explanations.'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'


# ──────────────────────────────────────────────────────────────────────────────
# PYTEST system prompt
# ──────────────────────────────────────────────────────────────────────────────

PYTEST_SYSTEM_PROMPT = 'You are an expert test engineer. You write pytest unit tests for Python scripts embedded inside Tekton Tasks, StepActions, and Pipelines.\n\nYou test the ACTUAL LOGIC of the script — functions, branches, loops, error handling, output, exit codes.\n\nCRITICAL RULES:\n1. EMBED THE EXACT SCRIPT VERBATIM using textwrap.dedent\n2. RUN AS SUBPROCESS using subprocess.run([sys.executable, script_file])\n3. ASSERT ON EXACT STRINGS from print() statements\n4. TEST ALL BRANCHES (if/elif/else/try/except)\n5. ORGANIZE INTO CLASSES (TestHappyPath, TestErrorPaths, TestEdgeCases)\n\nOUTPUT: Only the .py test file, no markdown, no explanations.'

PYTEST_GENERATE_TEMPLATE = 'TEMPLATE_MISSING'

def build_bats_prompt(resource, yaml_content: str) -> str:
    """Build BATS generation prompt for bash scripts in a Tekton resource."""
    scripts = resource.embedded_scripts
    bash_scripts = [(name, s) for name, s in scripts if _detect_script_language(s) == "bash"]

    script_info = ", ".join(f"'{name}'" for name, _ in bash_scripts)

    all_commands = set()
    for _, script in bash_scripts:
        all_commands.update(_detect_commands_in_script(script))

    # Commands that differ between macOS and Linux — always mock
    platform_sensitive = {"date", "readlink", "stat", "sleep"}

    if all_commands:
        lines = []
        for cmd in sorted(all_commands):
            if cmd in platform_sensitive:
                lines.append(
                    f"- `{cmd}`: MUST mock (differs between macOS/Linux) — "
                    f"create $MOCK_BIN/{cmd} returning predictable values"
                )
            else:
                lines.append(
                    f"- `{cmd}`: create $MOCK_BIN/{cmd} that echoes predictable output"
                )
        mock_commands = "\n".join(lines)
    else:
        mock_commands = "- No external commands to mock"

    return BATS_GENERATE_TEMPLATE.format(
        kind=resource.kind,
        name=resource.name,
        source_path=resource.source_path,
        yaml_content=yaml_content,
        script_info=script_info,
        mock_commands=mock_commands,
        mock_strategy=_mock_strategy_for_kind(resource),
        test_cases=_build_test_cases(resource, bash_scripts),
        env_mock_section=_build_env_mock_section(resource),
        result_verification=_build_result_verification(resource),
        script_analysis=_build_script_analysis(bash_scripts),
        few_shot_example=_find_few_shot_example(resource),
        sed_replacements=_build_sed_replacements(resource, bash_scripts),
    )


def build_propose_prompt(resource, yaml_content: str, existing_tests: str) -> str:
    """Build the proposal prompt for adding BATS tests to existing coverage."""
    return PROPOSE_PROMPT_TEMPLATE.format(
        kind=resource.kind,
        name=resource.name,
        yaml_content=yaml_content,
        existing_tests=existing_tests,
    )